<?php
return [
	"PUBLIC"=>[
		"ASSETS_START_PATH"=>"/"
	],
	"FILE_PATH"=>[
		"LOGO"=>"uploads/app/",
		"CATEGORY"=>"uploads/menu_icons/",
		"PRODUCT"=>"uploads/products/",
		"ICON"=>"uploads/icons/",
		"BANNER"=>"uploads/banners/",
		"SLIDERS"=>"uploads/sliders/"
	],
	"PRODUCT"=>[
		"TITLE_LENGTH"=>80,
		"DESCRIPTION_LENGTH"=>4000,
		"ALLOW_IMAGES"=>5,
		"ITEMS_PAGINATE"=>12,
		"NOTE_STRING_MAX"=>300,
		"HOME_PROUDUTS_LOAD"=>9,
		"DESCRIPTION_LENGTH_SHOW"=>15,//words
	],
	"SEPECIAL_CITIES"=>[
		"London"
	],
	"CREDIT_TOPUP_AMOUNT"=>[
		"MIN"=>50,
		"MAX"=>1500
	],
	"STAFF_SCHEDULE_ORDER_AT_LEAST_TIME"=>1,//Hours
	"ORDER"=>[
		"INIT_PAGINATE"=>5,
		"LIVE_UPDATE_EVERY"=>30000//minutes
	],
	"WEEK_DAYS"=>[
		"Monday",
		"Tuesday",
		"Wednesday",
		"Thursday",
		"Friday",
		"Saturday",
		"Sunday"
	],
	"ORDER_NOTIFICATIONS"=>[
		"MODES"=>[
			'Email',
			'Phone',
			'Both',
			'No'
		]
	],
	"PHONE_NUM_LENGTH"=>10,
	"DEFAULT_COUNTRY_CODE"=>44
];
?>